[build]
  base = "frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirections SPA (alternative à _redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200